### ISSUE TITLE
error opening files are not properly reported

### ISSUE THREAD

**Issue by pepdiz** [mittelmark/shtmlview#4]
[ej.txt](https://github.com/mittelmark/shtmlview/files/8290001/ej.txt)

The problem is described in the file attached (ej.txt) 

When you run it like   `$ tclsh ej.txt`  in shtmlview directory (my) expected behaviour is:

1- you get an error trying to open non existent file index.html
2- you open and browse file shtmlview.html
3- you open and browse README.md

but output is :

```
C:\Downloads\shtmlview>tclsh ej.tcl
You browsed C:/Downloads/shtmlview/shtmlview.html
H: C:/Downloads/shtmlview/shtmlview.html
F: C:/Downloads/shtmlview/shtmlview.html
```

and if you dropdownd the history combo list there are two files in history

This means file index.html is not loaded nor in history non in widget (because it doesn't exist) but there's no reported, I think this problem is solved, adding the line:

`puts stderr "Error: [file tail [regsub {#.*} $url {}]] does not exists!" `

after current line 1031  .  This way trying to render a non existing file is reported to stderr (maybe you don't want this behaviour since I saw all "puts stderr" are commented)

**Comment by mittelmark** [comment]
No, I do not want to print to stderr, I like to show the errors in the interface. The problem is that if the first browse file does not exists, the text widget remains empty. But there should be already in the status label on top a hint that the file does not exists. I now added as well a text message directly into the text widget.
